name = "Edentri Custom"
description = "A modern, responsive theme for Edentri with dark/light mode support"
homepage = "https://edentriweb.swiftscripters.workers.dev"
min_version = "0.116.0"

[author]
  name = "Edentri Team"
  homepage = "https://edentriweb.swiftscripters.workers.dev"

[features]
  responsive = true
  dark_mode = true
  video_hero = true